### ISSUE TITLE
Cast is not valid

### ISSUE THREAD

**Issue by mad-tunes** [AnthonyOSX/GO-Bot#106]
Hi,

Nice work. I've been having a play with the last couple of versions and have been getting on great, but in v0.0.5, I periodically get this:

```
2016-07-23 20:47:40.9922 | ERROR | GO_Bot.Views.MainWindow | System.InvalidCastException: Specified cast is not valid.
   at Google.Protobuf.JsonFormatter.IsDefaultValue(IFieldAccessor accessor, Object value)
   at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   at Google.Protobuf.JsonFormatter.Format(IMessage message, TextWriter writer)
   at Google.Protobuf.JsonFormatter.Format(IMessage message)
   at Google.Protobuf.JsonFormatter.ToDiagnosticString(IMessage message)
   at PokemonGo.RocketAPI.GeneratedCode.PokemonData.ToString() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\GeneratedCode\Payloads.cs:line 10760
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__12.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 367
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__14.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GO_Bot.Views.MainWindow.<<-ctor>b__11_1>d.MoveNext() in V:\GitHub\GO Bot\GO Bot\Views\MainWindow.xaml.cs:line 37
2016-07-23 20:47:41.0922 | INFO | GO_Bot.Views.MainWindow | Beginning to farm...
2016-07-23 20:47:41.1182 | INFO | API | Make sure Lat & Lng is right. Exit Program if not! Lat: *** Lng: ***
```

It seems to die for some reason and then restart, which is great behaviour, but will that make my location jump from where I was to my starting lat/long? Could that cause a 'soft ban'?

As it happens every couple of minutes, does it mean my location will never get far from my start position too?

**Comment by mad-tunes** [comment]
It doesn't seem to.

Sometimes searching doesn't restart, but that's less frequent.
