### ISSUE TITLE
Windows Error, Log Attached

### ISSUE THREAD

**Issue by WambulanceDriver** [AnthonyOSX/GO-Bot#176]
```
-------------- Error (2016-07-23 22:23:58.8391) --------------

Call Site: GO_Bot.App+<>c.<OnStartup>b__0_1
Type: System.IO.IOException
Message: The process cannot access the file 'C:\Users\Joe\Downloads\GO.Bot.v0-0-5\log.txt' because it is being used by another process.
Stack Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at PokemonGo.RocketAPI.Logger.Log(String message) in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Logger.cs:line 48
   at PokemonGo.RocketAPI.Logger.Write(String message, LogLevel level, ConsoleColor color) in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Logger.cs:line 42
   at PokemonGo.RocketAPI.Logic.Utils.Statistics.<UpdateConsoleTitle>d__21.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Utils\Statistics.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

FYI, I do not have a "C:\Users\Anthony\\*"

**Comment by Thomas-Maurer** [comment]
Well i think the problem is here : The process cannot access the file 'C:\Users\Joe\Downloads\GO.Bot.v0-0-5\log.txt' because it is being used by another process.

You try to run multiple instance of the bot ?

**Comment by fiorettijoe** [comment]
Nope, the bot was the only thing running at the time, I was asleep, woke up to find this error.

**Comment by Mantadox** [comment]
I posted on Exe crashing #174 before and i am using the bot for 2 accounts. i have several computers but i prefer to only use 1. Maybe it could create and use the files corresponding with the username. This way this error could be prevented "i think".

**Comment by kabesama** [comment]
I also got this problem. I have 20 bots active at the same time. It still works on 0.0.4, but it would be awesome if you could fix this.

**Comment by TheReggaeSheep** [comment]
If you have a folder for each account it works, just copy paste rename to Go-bot 2
