### ISSUE TITLE
Odd

### ISSUE THREAD

**Issue by enokisoju** [AnthonyOSX/GO-Bot#190]
Issue, doesn't work looping. Output from Error Log Below: 

Call Site: GO_Bot.Views.MainWindow+<<-ctor>b__11_1>d.MoveNext
Type: PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException
Message: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccountNotVerifiedException' was thrown.
Stack Trace:    at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GO_Bot.Views.MainWindow.<<-ctor>b__11_1>d.MoveNext() in V:\GitHub\GO Bot\GO Bot\Views\MainWindow.xaml.cs:line 37

I believe that the referenced directory calls could be an issue, for one I don't have a V drive and two my name isn't Anthony such as these two:

C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 146

V:\GitHub\GO Bot\GO Bot\Views\MainWindow.xaml.cs:line 37

**Comment by r4uschi** [comment]
i have the same problem https://github.com/AnthonyOSX/GO-Bot/issues/187

since i installed v0.5

**Comment by enokisoju** [comment]
Just odd that its referencing drive letters that I dont have and another username other than my own.

**Comment by shadowsyllvet** [comment]
Sounds like somebody "used" the master instead of cloning it?

**Comment by enokisoju** [comment]
So the Master is at this link? https://github.com/AnthonyOSX/GO-Bot/releases

**Comment by shadowsyllvet** [comment]
Honestly' I'm not as experienced a user of gihub as i should be. Mostly i was making a joke. When I used to use Minecraft mods from github you would occasionally hear about a commit or pull request that broke the service for other users because someone submitted something specific to their PC. This issue sounded vaguely like that.

**Comment by enokisoju** [comment]
Ah I see... Well I redownloaded and installed again. No worries.

**Comment by AnthonyOSX** [comment]
Make sure your account is authenticated.

**Comment by r4uschi** [comment]
Can u explain what u mean with "account is authenticated"? u mean verifiedwith email?

**Comment by iktoweya** [comment]
yes if you dont confirm your email then it gives that error. i just ran in to this error and did so and it works great.

**Comment by rayn21** [comment]
When you registered your PTC account, you should have received an email to verify your email address.  You have 2 days to do that or you can't login.  Check your inbox/spam folders.
