### ISSUE TITLE
Comething in the code is hard coded looking for this path

### ISSUE THREAD

**Issue by corvusine** [AnthonyOSX/GO-Bot#217]
2016-07-25 17:48:27.2282 | ERROR | GO_Bot.Views.MainWindow | Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at PokemonGo.RocketAPI.Helpers.JsonHelper.GetValue(String json, String key) in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Helpers\JsonHelper.cs:line 13
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__0.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<DoPtcLogin>d__26.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Client.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__10.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI.Logic\Logic.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GO_Bot.Views.MainWindow.<<-ctor>b__11_1>d.MoveNext() in V:\GitHub\GO Bot\GO Bot\Views\MainWindow.xaml.cs:line 37

**Comment by corvusine** [comment]
2016-07-25 22:36:09.4579 | INFO | API | [#0 of 25] retry request https://pgorelease.nianticlabs.com/plfe/276/rpc - Error: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\Anthony\Downloads\Pokemon-Go-Bot-master\Pokemon-Go-Bot-master\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 30

**Comment by timelf123** [comment]
It's not really hard coded, just showing the full trace from the perspective of the person who compiled the release. Looks like this is a PTC login error, make sure PTC is up on ispokemongodownornot.com
