### ISSUE TITLE
Crash on Start Up

### ISSUE THREAD

**Issue by rayn21** [AnthonyOSX/GO-Bot#37]
Exception in the log as follows --

Application: GO Bot.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(System.String, System.String, Boolean ByRef)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(System.String, System.String, System.String)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(System.String, System.String, System.String, Boolean)
   at System.Diagnostics.PerformanceCounter..ctor(System.String, System.String, System.String)
   at GO_Bot.Models.MainWindowModel..ctor()
   at GO_Bot.Views.MainWindow..ctor()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at GO_Bot.App.Main()

**Comment by mstok444** [comment]
Looks like it threw before the app even initialised, make sure you're running the correct .NET framework and try re-downloading the .zip release.

**Comment by MarcusOy** [comment]
Seems like an XML was read incorrectly? Or maybe the XML parser crashed when reading the XML file? Try re downloading the .zip like the above answer.

**Comment by ShawnHardwick** [comment]
I had the same error, but I checked the logs at C:\Users\<username>\GO Bot\Logs\MobiBot\Output and saw some errors that occur before the XamlException:

System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry

If you have this in your log as well, follow the below instructions:

Click Start, type cmd right click cmd.exe, and select Run as administrator. At the prompt, type `lodctr /r` and press ENTER.
Apparently, Windows keeps some counters cache in the registry at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\009 \ Counter+Help. If this cache becomes corrupted (has blank lines), you get the above errors - and lodctr /r rebuilds that cache.

`error: Unable to rebuild performance counter setting from system backup store, error code is 2`

then you instead need to run

`C:\windows\SysWOW64> lodctr /r`

after which you should get

Info: Successfully rebuilt performance counter setting from system backup store

Note this has to be done as administrator. 

Source: 
http://stackoverflow.com/questions/17980178/cannot-load-counter-name-data-because-an-invalid-index-exception

**Comment by Clintoxen** [comment]
If it crashes on start up even with the correct .net framework try this, it fixed it for me http://stackoverflow.com/questions/17980178/cannot-load-counter-name-data-because-an-invalid-index-exception

**Comment by AnthonyOSX** [comment]
Nice solution guys. Shame it's nothing I can solve within the bot itself :(
